#!/bin/bash

#Configura o ssh para não usar dns, (login mais rápido)
echo "UseDNS no" >>/etc/ssh/sshd_config

# configura interfaces de rede para a rede default do gateway
source /etc/sysconfig/network-scripts/ifcfg-enp0s3 
cat >/etc/sysconfig/network-scripts/ifcfg-enp0s3  <<EOL
# Generated by dracut initrd
NAME=enp0s3
DEVICE=enp0s3
ONBOOT=yes
NETBOOT=yes
UUID=$UUID
IPV6INIT=yes
BOOTPROTO=none
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
IPADDR=192.168.1.1
PREFIX=24
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
ZONE=public
GATEWAY=192.168.1.1
EOL

source /etc/sysconfig/network-scripts/ifcfg-enp0s8 
cat >/etc/sysconfig/network-scripts/ifcfg-enp0s8  <<EOL
# Generated by dracut initrd
NAME=enp0s8
DEVICE=enp0s8
ONBOOT=yes
NETBOOT=yes
UUID=$UUID
IPV6INIT=yes
BOOTPROTO=none
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
IPADDR=192.168.99.5
PREFIX=24
GATEWAY=192.168.99.1
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
DNS1=192.168.99.1
DOMAIN=cluster.nodes
ZONE=public
EOL

# habilita proxy scks para a instalação
export http_proxy=socks5://192.168.99.1:11000
export https_proxy=socks5://192.168.99.1:11000

# instala pacotes de base necessários
yum install -y make bzip2 openssh-clients nano htop wget automake gcc cpp glibc-devel glibc-headers \
glibc-kernheaders glibc glibc-common libgcc zlib-devel openssl-devel readline-devel git 

wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
rpm -ivh epel-release-latest-7.noarch.rpm
yum groupinstall "Development Tools" -y
yum install libevent-devel libevent -y
yum update -y

# instala o socksnatd a partir dos fontes
cd /tmp
git clone https://github.com/rssnsj/socksnat
cd socksnat/src
make
make install

# configura o socksnatd para o ip do central
echo "default = 192.168.99.1:11000" > /etc/socksnatd.conf

# cria o script de inicialização o gateway transparente socks
cat >/usr/local/bin/transparent-gateway  <<EOL
#!/bin/bash

# disabilita firewall-cmd
systemctl disable firewall-cmd
systemctl stop firewall-cmd

# habilita forward
echo net.ipv4.ip_forward =1 > /etc/sysctl.conf

# limpa iptables 
iptables -F
iptables -t nat -F

# redireciona para o proxy transparente
iptables -t nat -A PREROUTING -s 192.168.1.0/24 ! -d 192.168.0.0/16  -p tcp -j DNAT --to 192.168.1.1:7070

# habilita mascaramento de entrada e saida 
iptables -t nat -A POSTROUTING  -o enp0s8 -j MASQUERADE
iptables -t nat -A POSTROUTING  -o enp0s3 -j MASQUERADE

# inicia o socksnatd
/usr/sbin/socksnatd
EOL

# configura o script de inicialização do gateway transparent
cat >/etc/systemd/system/transparent-gateway.service  <<EOL
[Unit]
Description=transparent gateway
After=network.target

[Service]
ExecStart=/usr/local/bin/transparent-gateway

[Install]
WantedBy=multi-user.target
EOL


chmod +x /usr/local/bin/transparent-gateway

# habilita o gateway transparente no systemd 
systemctl enable transparent-gateway
